### ISSUE TITLE
Catching errors

### ISSUE THREAD

**Issue by keolo** [swiftype/meta_events#17]
What's the best way to rescue a `Errno::ECONNRESET` error? This error can be caused from the mixpanel api being down.

Right now I'm doing something like the following in a controller which doesn't feel quite right:

    def track
      MetaEvents::Tracker.new(
        distinct_id,
        request.ip,
        implicit_properties: implicit_properties
      )
    rescue Errno::ECONNRESET => error
      MetaEvents::Tracker.default_event_receivers = [MetaEvents::TestReceiver.new]
    end

**Comment by davidkelley** [comment]
If the Mixpanel API is down, you want to avoid losing the events that are firing by sending them to the TestReceiver.

Take a look at [performance-and-asynchronousness](https://github.com/swiftype/meta_events#performance-and-asynchronousness), in the documentation. If you enqueue the job inside delayed_job for example, the job will fail to complete until the Mixpanel API is back up. -- However, unmentioned in the documentation, is that when using background jobs to send events, be sure to inject the timestamp for the event as a property.

**Comment by keolo** [comment]
Makes sense. Thanks!
